apiVersion: v1
kind: Service
metadata:
  name: planificacion-service
  namespace: diplomado-m3
spec:
  type: ClusterIP
  selector:
    app: planificacion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
